name: 🐛 Bug Report
description: Report a problem in VideOCR
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in VideOCR!  
        Please fill out the following information so we can reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of VideOCR
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the problem
      placeholder: e.g. "App crashes when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open the app
        2. Load video file
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs
      description: Add screenshots, error logs, or console output
      placeholder: Drag and drop screenshots or paste logs here
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 🖥 Environment
      description: Please specify the details of your setup.
      placeholder: |
        OS: Windows 11 / Ubuntu 22.04
        VideOCR version: 1.4.0
        GPU model: NVIDIA RTX 3060 (leave blank if using CPU version)
    validations:
      required: true
