name: 💡 Feature Request
description: Suggest a new feature or improvement for VideOCR
title: "[Feature request] "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for VideOCR!  
        Please fill out the following information.

  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: What would you like to see added or changed?
    validations:
      required: true
